/**
 * Fallback rows used when Supabase env vars are absent or a read fails.
 *
 * Stage 0 seeds the same kind of data into Postgres; this exists so the UI is
 * demoable before anyone has wired credentials, and so a dead database during
 * judging degrades to a populated page instead of an empty one.
 */
import type { ReportRow } from "@/lib/types";

const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const DEMO_REPORTS: ReportRow[] = [
  {
    id: "demo-1",
    created_at: minutesAgo(24),
    media_url: null,
    media_type: null,
    raw_text: "Huge pothole outside my gate, water collects in it every night.",
    transcript: null,
    issue_type: "pothole",
    summary: "Large water-filled pothole on the service lane causing bike accidents",
    area_tag: "gulshan_e_iqbal",
    authority_slug: "kmc",
    authority_assigned: "Karachi Metropolitan Corporation",
    complaint_text: "",
    language: "en",
    upvotes: 128,
    email_status: "sent",
  },
  {
    id: "demo-2",
    created_at: minutesAgo(95),
    media_url: null,
    media_type: null,
    raw_text: "Sewage overflowing near the main market for three days.",
    transcript: null,
    issue_type: "sewage",
    summary: "Sewage line overflowing into the market road for three days",
    area_tag: "lyari",
    authority_slug: "kwsb",
    authority_assigned: "Karachi Water & Sewerage Board",
    complaint_text: "",
    language: "en",
    upvotes: 94,
    email_status: "sent",
  },
  {
    id: "demo-3",
    created_at: minutesAgo(180),
    media_url: null,
    media_type: null,
    raw_text: "کچرے کا ڈھیر ہفتے سے نہیں اٹھایا گیا",
    transcript: null,
    issue_type: "garbage",
    summary: "Uncollected garbage pile outside the residential block for a week",
    area_tag: "north_nazimabad",
    authority_slug: "sswmb",
    authority_assigned: "Sindh Solid Waste Management Board",
    complaint_text: "",
    language: "ur",
    upvotes: 71,
    email_status: null,
  },
  {
    id: "demo-4",
    created_at: minutesAgo(260),
    media_url: null,
    media_type: null,
    raw_text: "Shops have taken over the entire footpath, no space to walk.",
    transcript: null,
    issue_type: "encroachment",
    summary: "Footpath fully encroached by shop extensions forcing pedestrians onto the road",
    area_tag: "saddar",
    authority_slug: "tma",
    authority_assigned: "Town Municipal Administration",
    complaint_text: "",
    language: "en",
    upvotes: 55,
    email_status: null,
  },
  {
    id: "demo-5",
    created_at: minutesAgo(420),
    media_url: null,
    media_type: null,
    raw_text: "No water supply in our lane since Monday.",
    transcript: null,
    issue_type: "water",
    summary: "No piped water supply to the lane since Monday, tankers being bought privately",
    area_tag: "clifton",
    authority_slug: "cbc",
    authority_assigned: "Cantonment Board Clifton",
    complaint_text: "",
    language: "en",
    upvotes: 38,
    email_status: "sent",
  },
  {
    id: "demo-6",
    created_at: minutesAgo(600),
    media_url: null,
    media_type: null,
    raw_text: "Broken road near the flyover, dust everywhere.",
    transcript: null,
    issue_type: "pothole",
    summary: "Broken carriageway near the flyover throwing up dust across the junction",
    area_tag: "korangi",
    authority_slug: "kmc",
    authority_assigned: "Karachi Metropolitan Corporation",
    complaint_text: "",
    language: "en",
    upvotes: 21,
    email_status: null,
  },
];
